version: '3.1'
services:
  code:
    image: 127.0.0.1:5000/code
    user: 1000:1000
    build:
      context: ..
      dockerfile: ./make/Dockerfile
    command: tail -F anything
    ports:
      - 3000:3000
      - 3001:3001
